name: Create PR Env

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - run: echo "BRANCH_NAME=${GITHUB_REF_NAME,,}" >>${GITHUB_ENV}

    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Install dependencies
      run: yarn

    - name: Deploy stack
      run: yarn sst deploy --stage ${BRANCH_NAME}
      env:
        DOMAIN_NAME: ${BRANCH_NAME}.pocok.biz
        API_URL: https://${BRANCH_NAME}.pocok.biz
        MAILGUN_DOMAIN: mg.pocok.biz
        MAILGUN_SENDER: ${BRANCH_NAME}@mg.pocok.biz
        EMAIL_RECIPIENT: mate.donka@apexlab.io
        MAILGUN_API_KEY: ${{ secrets.PROD_MAILGUN_API_KEY }}
        TYPLESS_TOKEN: ${{ secrets.PROD_TYPLESS_TOKEN }}
        TYPLESS_DOC_TYPE: ${{ secrets.PROD_TYPLESS_DOC_TYPE }}
        PROCESS_INVOICE_LAMBDA_TIMEOUT_SEC: 30
    
    - name: Comment
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Deployed to ${BRANCH_NAME}.pocok.biz'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
