name: Destroy PR Env

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug variables
      uses: rlespinasse/github-slug-action@v4

    - name: Set STAGE variable in environment for next steps
      run: echo "STAGE=pr-${{ github.event.number }}-${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Install dependencies
      run: yarn

    - name: Destroy stack
      run: yarn sst remove --stage ${STAGE}
      env:
        DOMAIN_NAME: ${{STAGE}}.pocok.biz
        PROCESS_INVOICE_LAMBDA_TIMEOUT_SEC: 30