name: PR checks

on: pull_request

jobs:
  go_build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./src/...

    - name: Test
      run: go test -v ./src/...

  amp_validate:
    name: Validate AMP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install amphtml-validator
      run: yarn global add amphtml-validator
    
    - name: Validate
      run: yarn amp-validate

  golangci:
    name: Lint GO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
